#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34014
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("PointCloud.Resource", IsApplication=true)]

namespace PointCloud
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
			global::TangoUtils.Resource.String.ApplicationName = global::PointCloud.Resource.String.ApplicationName;
			global::TangoUtils.Resource.String.Hello = global::PointCloud.Resource.String.Hello;
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Dimension
		{
			
			// aapt resource value: 0x7f050000
			public const int activity_horizontal_margin = 2131034112;
			
			// aapt resource value: 0x7f050001
			public const int activity_vertical_margin = 2131034113;
			
			static Dimension()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Dimension()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int Icon = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int Splash = 2130837505;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f070003
			public const int appversion = 2131165187;
			
			// aapt resource value: 0x7f07000a
			public const int averageZ = 2131165194;
			
			// aapt resource value: 0x7f070007
			public const int deltatime = 2131165191;
			
			// aapt resource value: 0x7f07000d
			public const int first_person_button = 2131165197;
			
			// aapt resource value: 0x7f07000c
			public const int frameDelta = 2131165196;
			
			// aapt resource value: 0x7f070000
			public const int gl_surface_view = 2131165184;
			
			// aapt resource value: 0x7f070001
			public const int linearlayout = 2131165185;
			
			// aapt resource value: 0x7f07000b
			public const int pointCount = 2131165195;
			
			// aapt resource value: 0x7f070008
			public const int pose = 2131165192;
			
			// aapt resource value: 0x7f070006
			public const int posecount = 2131165190;
			
			// aapt resource value: 0x7f070009
			public const int quat = 2131165193;
			
			// aapt resource value: 0x7f070005
			public const int status = 2131165189;
			
			// aapt resource value: 0x7f070004
			public const int tangoevent = 2131165188;
			
			// aapt resource value: 0x7f07000e
			public const int third_person_button = 2131165198;
			
			// aapt resource value: 0x7f07000f
			public const int top_down_button = 2131165199;
			
			// aapt resource value: 0x7f070002
			public const int version = 2131165186;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int activity_jpoint_cloud = 2130903040;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f040001
			public const int ApplicationName = 2130968577;
			
			// aapt resource value: 0x7f040000
			public const int Hello = 2130968576;
			
			// aapt resource value: 0x7f04001a
			public const int NA = 2130968602;
			
			// aapt resource value: 0x7f040017
			public const int TangoError = 2130968599;
			
			// aapt resource value: 0x7f040018
			public const int TangoOutOfDateException = 2130968600;
			
			// aapt resource value: 0x7f040002
			public const int app_name = 2130968578;
			
			// aapt resource value: 0x7f040006
			public const int appversion = 2130968582;
			
			// aapt resource value: 0x7f040013
			public const int autoresetoff = 2130968595;
			
			// aapt resource value: 0x7f040012
			public const int autoreseton = 2130968594;
			
			// aapt resource value: 0x7f040014
			public const int averageZ = 2130968596;
			
			// aapt resource value: 0x7f04000b
			public const int deltatime = 2130968587;
			
			// aapt resource value: 0x7f04000e
			public const int first_person = 2130968590;
			
			// aapt resource value: 0x7f040016
			public const int frameDelta = 2130968598;
			
			// aapt resource value: 0x7f040003
			public const int menu_name = 2130968579;
			
			// aapt resource value: 0x7f040019
			public const int motiontrackingpermission = 2130968601;
			
			// aapt resource value: 0x7f040015
			public const int pointCount = 2130968597;
			
			// aapt resource value: 0x7f04000c
			public const int pose = 2130968588;
			
			// aapt resource value: 0x7f040009
			public const int posecount = 2130968585;
			
			// aapt resource value: 0x7f04000d
			public const int quat = 2130968589;
			
			// aapt resource value: 0x7f040005
			public const int serviceversion = 2130968581;
			
			// aapt resource value: 0x7f040011
			public const int start = 2130968593;
			
			// aapt resource value: 0x7f040008
			public const int start2device = 2130968584;
			
			// aapt resource value: 0x7f04000a
			public const int status = 2130968586;
			
			// aapt resource value: 0x7f040007
			public const int tangoevent = 2130968583;
			
			// aapt resource value: 0x7f04000f
			public const int third_person = 2130968591;
			
			// aapt resource value: 0x7f040010
			public const int top_down = 2130968592;
			
			// aapt resource value: 0x7f040004
			public const int vertex_count = 2130968580;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
		
		public partial class Style
		{
			
			// aapt resource value: 0x7f060000
			public const int AppBaseTheme = 2131099648;
			
			// aapt resource value: 0x7f060001
			public const int AppTheme = 2131099649;
			
			static Style()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Style()
			{
			}
		}
	}
}
#pragma warning restore 1591
