#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("com.projecttango.pointcloudcsharp.Resource", IsApplication=true)]

namespace com.projecttango.pointcloudcsharp
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Dimension
		{
			
			// aapt resource value: 0x7f040000
			public const int activity_horizontal_margin = 2130968576;
			
			// aapt resource value: 0x7f040001
			public const int activity_vertical_margin = 2130968577;
			
			static Dimension()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Dimension()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int Icon = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int Splash = 2130837505;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f070003
			public const int appversion = 2131165187;
			
			// aapt resource value: 0x7f07000a
			public const int averageZ = 2131165194;
			
			// aapt resource value: 0x7f070007
			public const int deltatime = 2131165191;
			
			// aapt resource value: 0x7f07000d
			public const int first_person_button = 2131165197;
			
			// aapt resource value: 0x7f07000c
			public const int frameDelta = 2131165196;
			
			// aapt resource value: 0x7f070000
			public const int gl_surface_view = 2131165184;
			
			// aapt resource value: 0x7f070001
			public const int linearlayout = 2131165185;
			
			// aapt resource value: 0x7f07000b
			public const int pointCount = 2131165195;
			
			// aapt resource value: 0x7f070008
			public const int pose = 2131165192;
			
			// aapt resource value: 0x7f070006
			public const int posecount = 2131165190;
			
			// aapt resource value: 0x7f070009
			public const int quat = 2131165193;
			
			// aapt resource value: 0x7f070005
			public const int status = 2131165189;
			
			// aapt resource value: 0x7f070004
			public const int tangoevent = 2131165188;
			
			// aapt resource value: 0x7f07000e
			public const int third_person_button = 2131165198;
			
			// aapt resource value: 0x7f07000f
			public const int top_down_button = 2131165199;
			
			// aapt resource value: 0x7f070002
			public const int version = 2131165186;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int activity_jpoint_cloud = 2130903040;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f050018
			public const int NA = 2131034136;
			
			// aapt resource value: 0x7f050015
			public const int TangoError = 2131034133;
			
			// aapt resource value: 0x7f050016
			public const int TangoOutOfDateException = 2131034134;
			
			// aapt resource value: 0x7f050000
			public const int app_name = 2131034112;
			
			// aapt resource value: 0x7f050004
			public const int appversion = 2131034116;
			
			// aapt resource value: 0x7f050011
			public const int autoresetoff = 2131034129;
			
			// aapt resource value: 0x7f050010
			public const int autoreseton = 2131034128;
			
			// aapt resource value: 0x7f050012
			public const int averageZ = 2131034130;
			
			// aapt resource value: 0x7f050009
			public const int deltatime = 2131034121;
			
			// aapt resource value: 0x7f05000c
			public const int first_person = 2131034124;
			
			// aapt resource value: 0x7f050014
			public const int frameDelta = 2131034132;
			
			// aapt resource value: 0x7f050001
			public const int menu_name = 2131034113;
			
			// aapt resource value: 0x7f050017
			public const int motiontrackingpermission = 2131034135;
			
			// aapt resource value: 0x7f050013
			public const int pointCount = 2131034131;
			
			// aapt resource value: 0x7f05000a
			public const int pose = 2131034122;
			
			// aapt resource value: 0x7f050007
			public const int posecount = 2131034119;
			
			// aapt resource value: 0x7f05000b
			public const int quat = 2131034123;
			
			// aapt resource value: 0x7f050003
			public const int serviceversion = 2131034115;
			
			// aapt resource value: 0x7f05000f
			public const int start = 2131034127;
			
			// aapt resource value: 0x7f050006
			public const int start2device = 2131034118;
			
			// aapt resource value: 0x7f050008
			public const int status = 2131034120;
			
			// aapt resource value: 0x7f050005
			public const int tangoevent = 2131034117;
			
			// aapt resource value: 0x7f05000d
			public const int third_person = 2131034125;
			
			// aapt resource value: 0x7f05000e
			public const int top_down = 2131034126;
			
			// aapt resource value: 0x7f050002
			public const int vertex_count = 2131034114;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
		
		public partial class Style
		{
			
			// aapt resource value: 0x7f060000
			public const int AppBaseTheme = 2131099648;
			
			// aapt resource value: 0x7f060001
			public const int AppTheme = 2131099649;
			
			static Style()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Style()
			{
			}
		}
	}
}
#pragma warning restore 1591
