#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34014
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("com.projecttango.areadescriptioncsharp.Resource", IsApplication=true)]

namespace com.projecttango.areadescriptioncsharp
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
			global::TangoUtils.Resource.String.ApplicationName = global::com.projecttango.areadescriptioncsharp.Resource.String.ApplicationName;
			global::TangoUtils.Resource.String.Hello = global::com.projecttango.areadescriptioncsharp.Resource.String.Hello;
		}
		
		public partial class Array
		{
			
			// aapt resource value: 0x7f060000
			public const int SetDialogMenuItemsAPISpace = 2131099648;
			
			// aapt resource value: 0x7f060001
			public const int SetDialogMenuItemsAppSpace = 2131099649;
			
			static Array()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Array()
			{
			}
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Dimension
		{
			
			// aapt resource value: 0x7f050000
			public const int activity_horizontal_margin = 2131034112;
			
			// aapt resource value: 0x7f050001
			public const int activity_vertical_margin = 2131034113;
			
			static Dimension()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Dimension()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int Icon = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int Splash = 2130837505;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f080025
			public const int ADFListView = 2131230757;
			
			// aapt resource value: 0x7f08001a
			public const int AbsoluteLayout1 = 2131230746;
			
			// aapt resource value: 0x7f08001f
			public const int Ok = 2131230751;
			
			// aapt resource value: 0x7f08001c
			public const int RelativeLayout = 2131230748;
			
			// aapt resource value: 0x7f08001d
			public const int RelativeLayout1 = 2131230749;
			
			// aapt resource value: 0x7f08000c
			public const int adf2deviceDeltatime = 2131230732;
			
			// aapt resource value: 0x7f08000d
			public const int adf2devicePose = 2131230733;
			
			// aapt resource value: 0x7f08000b
			public const int adf2devicePosecount = 2131230731;
			
			// aapt resource value: 0x7f08000e
			public const int adf2deviceQuat = 2131230734;
			
			// aapt resource value: 0x7f08000a
			public const int adf2deviceStatus = 2131230730;
			
			// aapt resource value: 0x7f080011
			public const int adf2startDeltatime = 2131230737;
			
			// aapt resource value: 0x7f080012
			public const int adf2startPose = 2131230738;
			
			// aapt resource value: 0x7f080010
			public const int adf2startPosecount = 2131230736;
			
			// aapt resource value: 0x7f080013
			public const int adf2startQuat = 2131230739;
			
			// aapt resource value: 0x7f08000f
			public const int adf2startStatus = 2131230735;
			
			// aapt resource value: 0x7f080029
			public const int adfName = 2131230761;
			
			// aapt resource value: 0x7f080003
			public const int appversion = 2131230723;
			
			// aapt resource value: 0x7f08001e
			public const int cancel = 2131230750;
			
			// aapt resource value: 0x7f080018
			public const int first_person_button = 2131230744;
			
			// aapt resource value: 0x7f080000
			public const int gl_surface_view = 2131230720;
			
			// aapt resource value: 0x7f080023
			public const int learningmode = 2131230755;
			
			// aapt resource value: 0x7f080001
			public const int linearLayout1 = 2131230721;
			
			// aapt resource value: 0x7f080022
			public const int loadadf = 2131230754;
			
			// aapt resource value: 0x7f080020
			public const int name = 2131230752;
			
			// aapt resource value: 0x7f08001b
			public const int pathView1 = 2131230747;
			
			// aapt resource value: 0x7f080019
			public const int saveAdf = 2131230745;
			
			// aapt resource value: 0x7f080024
			public const int start = 2131230756;
			
			// aapt resource value: 0x7f080007
			public const int start2deviceDeltatime = 2131230727;
			
			// aapt resource value: 0x7f080008
			public const int start2devicePose = 2131230728;
			
			// aapt resource value: 0x7f080006
			public const int start2devicePosecount = 2131230726;
			
			// aapt resource value: 0x7f080009
			public const int start2deviceQuat = 2131230729;
			
			// aapt resource value: 0x7f080005
			public const int start2deviceStatus = 2131230725;
			
			// aapt resource value: 0x7f080004
			public const int tangoevent = 2131230724;
			
			// aapt resource value: 0x7f080017
			public const int third_person_button = 2131230743;
			
			// aapt resource value: 0x7f080016
			public const int top_down_button = 2131230742;
			
			// aapt resource value: 0x7f080014
			public const int uuid = 2131230740;
			
			// aapt resource value: 0x7f080015
			public const int uuidCount = 2131230741;
			
			// aapt resource value: 0x7f080021
			public const int uuidDisplay = 2131230753;
			
			// aapt resource value: 0x7f080026
			public const int uuidListViewLinearLayout = 2131230758;
			
			// aapt resource value: 0x7f080027
			public const int uuidlistviewAPI = 2131230759;
			
			// aapt resource value: 0x7f080028
			public const int uuidlistviewApplicationSpace = 2131230760;
			
			// aapt resource value: 0x7f080002
			public const int version = 2131230722;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int activity_area_learning = 2130903040;
			
			// aapt resource value: 0x7f030001
			public const int last_adf_canvasview = 2130903041;
			
			// aapt resource value: 0x7f030002
			public const int last_adf_path = 2130903042;
			
			// aapt resource value: 0x7f030003
			public const int set_name_dialog = 2130903043;
			
			// aapt resource value: 0x7f030004
			public const int start_activity = 2130903044;
			
			// aapt resource value: 0x7f030005
			public const int uuid_listview = 2130903045;
			
			// aapt resource value: 0x7f030006
			public const int uuid_view = 2130903046;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f040001
			public const int ApplicationName = 2130968577;
			
			// aapt resource value: 0x7f040000
			public const int Hello = 2130968576;
			
			// aapt resource value: 0x7f040009
			public const int adf2device = 2130968585;
			
			// aapt resource value: 0x7f040008
			public const int adf2start = 2130968584;
			
			// aapt resource value: 0x7f040022
			public const int adf_exists_api_space = 2130968610;
			
			// aapt resource value: 0x7f040021
			public const int adf_exists_app_space = 2130968609;
			
			// aapt resource value: 0x7f040020
			public const int adf_save = 2130968608;
			
			// aapt resource value: 0x7f04001a
			public const int api_adfs = 2130968602;
			
			// aapt resource value: 0x7f040002
			public const int app_name = 2130968578;
			
			// aapt resource value: 0x7f040005
			public const int app_version = 2130968581;
			
			// aapt resource value: 0x7f04001b
			public const int application_adfs = 2130968603;
			
			// aapt resource value: 0x7f040027
			public const int arealearning_permission = 2130968615;
			
			// aapt resource value: 0x7f040014
			public const int cancel = 2130968596;
			
			// aapt resource value: 0x7f04000c
			public const int delta_time = 2130968588;
			
			// aapt resource value: 0x7f04000f
			public const int first_person = 2130968591;
			
			// aapt resource value: 0x7f040033
			public const int latest_adf_is = 2130968627;
			
			// aapt resource value: 0x7f04002b
			public const int learningmode_off = 2130968619;
			
			// aapt resource value: 0x7f04002c
			public const int learningmode_on = 2130968620;
			
			// aapt resource value: 0x7f04002e
			public const int loadadf_off = 2130968622;
			
			// aapt resource value: 0x7f04002d
			public const int loadadf_on = 2130968621;
			
			// aapt resource value: 0x7f040019
			public const int manage_adfs = 2130968601;
			
			// aapt resource value: 0x7f040003
			public const int menu_name = 2130968579;
			
			// aapt resource value: 0x7f040025
			public const int metadata_not_read = 2130968613;
			
			// aapt resource value: 0x7f040026
			public const int motiontracking_permission = 2130968614;
			
			// aapt resource value: 0x7f04002a
			public const int na = 2130968618;
			
			// aapt resource value: 0x7f040016
			public const int name = 2130968598;
			
			// aapt resource value: 0x7f040023
			public const int no_adfs_tango_error = 2130968611;
			
			// aapt resource value: 0x7f040024
			public const int no_permissions = 2130968612;
			
			// aapt resource value: 0x7f040028
			public const int no_uuid = 2130968616;
			
			// aapt resource value: 0x7f04001f
			public const int no_uuid_tango_error = 2130968607;
			
			// aapt resource value: 0x7f040029
			public const int number_of_adfs = 2130968617;
			
			// aapt resource value: 0x7f040017
			public const int ok = 2130968599;
			
			// aapt resource value: 0x7f04000d
			public const int pose = 2130968589;
			
			// aapt resource value: 0x7f04000a
			public const int pose_count = 2130968586;
			
			// aapt resource value: 0x7f04002f
			public const int pose_initializing = 2130968623;
			
			// aapt resource value: 0x7f040031
			public const int pose_invalid = 2130968625;
			
			// aapt resource value: 0x7f040032
			public const int pose_unknown = 2130968626;
			
			// aapt resource value: 0x7f040030
			public const int pose_valid = 2130968624;
			
			// aapt resource value: 0x7f04000e
			public const int quat = 2130968590;
			
			// aapt resource value: 0x7f040015
			public const int save_adf = 2130968597;
			
			// aapt resource value: 0x7f040004
			public const int service_version = 2130968580;
			
			// aapt resource value: 0x7f040013
			public const int set_name_dialogTitle = 2130968595;
			
			// aapt resource value: 0x7f040012
			public const int start = 2130968594;
			
			// aapt resource value: 0x7f040007
			public const int start2device = 2130968583;
			
			// aapt resource value: 0x7f040018
			public const int start_config = 2130968600;
			
			// aapt resource value: 0x7f04000b
			public const int status = 2130968587;
			
			// aapt resource value: 0x7f04001d
			public const int tango_error = 2130968605;
			
			// aapt resource value: 0x7f040006
			public const int tango_event = 2130968582;
			
			// aapt resource value: 0x7f04001e
			public const int tango_out_of_date_exception = 2130968606;
			
			// aapt resource value: 0x7f040010
			public const int third_person = 2130968592;
			
			// aapt resource value: 0x7f040011
			public const int top_down = 2130968593;
			
			// aapt resource value: 0x7f04001c
			public const int uuid = 2130968604;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
		
		public partial class Style
		{
			
			// aapt resource value: 0x7f070000
			public const int AppBaseTheme = 2131165184;
			
			// aapt resource value: 0x7f070001
			public const int AppTheme = 2131165185;
			
			// aapt resource value: 0x7f070003
			public const int Theme_Icon = 2131165187;
			
			// aapt resource value: 0x7f070002
			public const int Theme_Splash = 2131165186;
			
			static Style()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Style()
			{
			}
		}
	}
}
#pragma warning restore 1591
